### ISSUE TITLE
Avoir les users d'un service

### ISSUE THREAD

**Issue by Joris-G** [Joris-G/daherApp#16]
J'ai utilisé l'api usine.
![image](https://user-images.githubusercontent.com/66126635/164243169-568f781b-238b-4fed-be44-0b11863cb291.png)
C'est le résultat d'un GET sur un service.
J'aimerai avoir l'objet user complet de manière à pouvoir filtrer encore par les attributs des users.
Le but final est d'afficher une info bulle du nombre de nouveaux utilisateurs dont le compte n'est pas validé sur le service.

![image](https://user-images.githubusercontent.com/66126635/164243588-29dd1716-773a-4380-9ca8-8dfe611ff6f9.png)

**Comment by Franck-Dev** [comment]
OK
<img width="659" alt="image" src="https://user-images.githubusercontent.com/52229344/167139549-5fe37b37-086f-4de4-b8f6-3d1aa07733b0.png">
