### ISSUE TITLE
Impossible d'ajouter utilisateur dans groupe d'affectation

### ISSUE THREAD

**Issue by Joris-G** [Joris-G/daherApp#18]
![image](https://user-images.githubusercontent.com/66126635/164281820-0dcdfc92-26f5-444d-84a0-646dc0d6f4b7.png)

![image](https://user-images.githubusercontent.com/66126635/164281871-fe9d1452-f0a8-4b3f-bf67-8e04bde7c1fe.png)

Response : 
Le user ajouté n'apparait pas dans la liste

![image](https://user-images.githubusercontent.com/66126635/164281952-206d72c0-524c-446d-bdd7-9f7f4bfd396b.png)

**Comment by Franck-Dev** [comment]
Il faut donner un tableau de users si tu veux plusieurs users dans la population.
Le PATCH remplace un seul ensemble de données, mais en l'écrasant par la nouvelle donnée

**Comment by Franck-Dev** [comment]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/52229344/164302244-a9742669-5d82-46d0-aacc-ead3f93abd49.png">
